#ifndef CONSTANTS_H
#define CONSTANTS_H

#include <simlib.h>

/**
 * Soubor definujici konstanty simulace
 */

#define SIMULATION_TIME_IN_DAYS (30)
#define SIMULATION_END_TIME (SIMULATION_TIME_IN_DAYS*24*60)

#define TRAIN_CAPACITY (350)

#define DAY_LENGTH (24*60)
#define DAY_START (5*60)
#define DAY_END (21*60)

#define WEEK_LENGTH (7*24*60)
#define WORK_WEEK_START (0)
#define WORK_WEEK_END (5*24*60)

#define NORMAL_PATH_TIME (40)
#define TISNOV_KURIM_TIME (11)
#define KURIM_BRNO_TIME (26)

#define TRAIN_DAY_TIME_DISTRIBUTION (27)
#define TRAIN_NIGHT_TIME_DISTRIBUTION (60)
#define TRAIN_DAY_WEEKEND_TIME_DISTRIBUTION (40)
#define TRAIN_NIGHT_WEEKEND_TIME_DISTRIBUTION (60)

#define OUT_IN_KURIM_PROB (0.3)

#define PROB_TO_LEAVE (0.3)

#define WORK_DAY_WAITING (Uniform(40, 60))
#define WORK_NIGHT_WAITING (Uniform(70, 90))
#define WEEKEND_DAY_WAITING (Uniform(50, 70))
#define WEEKEND_NIGHT_WAITING (Uniform(70, 110))

#define COMMUTER_WORK_DAY_PROB (0.2)
#define COMMUTER_KURIM_WORK_DAY_PROB (1)

#define COMMUTER_WORK_NIGHT_PROB (15)
#define COMMUTER_KURIM_WORK_NIGHT_PROB (20)

#define COMMUTER_WEEKEND_DAY_PROB (2)
#define COMMUTER_KURIM_WEEKEND_DAY_PROB (4)

#define COMMUTER_WEEKEND_NIGHT_PROB (7)
#define COMMUTER_KURIM_WEEKEND_NIGHT_PROB (10)



#endif